version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install_pipenv
            make init
      - add_ssh_keys:
          fingerprints:
            - "eb:56:96:1e:9d:3a:df:59:d7:28:94:50:e5:89:9b:14"
      - run:
          name: Test
          command: |
            make test
  track-all:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install_pipenv
            make init
      - add_ssh_keys:
          fingerprints:
            - "eb:56:96:1e:9d:3a:df:59:d7:28:94:50:e5:89:9b:14"
      - run:
          name: Track all
          command: |
            make
  track-often:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install_pipenv
            make init
      - add_ssh_keys:
          fingerprints:
            - "eb:56:96:1e:9d:3a:df:59:d7:28:94:50:e5:89:9b:14"
      - run:
          name: Track often
          command: |
            make often
  track-rarely:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install_pipenv
            make init
      - add_ssh_keys:
          fingerprints:
            - "eb:56:96:1e:9d:3a:df:59:d7:28:94:50:e5:89:9b:14"
      - run:
          name: Track rarely
          command: |
            make rarely

workflows:
  version: 2
  # 1st
  on-commit:
    jobs:
      - test
      - track-all:
          requires:
            - test
          filters:
            branches:
              only:
                - master
  # 2nd
  at-1100-and-1800-UTC-every-day:
    triggers:
      - schedule:
          cron: "0 11,18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - track-often
  # 3rd
  at-1000-UTC-every-wednesday:
    triggers:
      - schedule:
          cron: "0 10 * * 3"
          filters:
            branches:
              only:
                - master
    jobs:
      - track-rarely
