version: 2
jobs:
  track-and-publish:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            make install_pipenv
            make init
      - add_ssh_keys:
          fingerprints:
            - "a9:17:81:9b:4e:22:76:a8:7b:14:9b:36:6d:a3:7a:d6"
      - run:
          name: Configure git user
          command: |
            git config user.email "ooz@users.noreply.github.com"
            git config user.name "ooz"
      - run:
          name: Build and publish
          command: |
            make publish

workflows:
  version: 2
  on-commit:
    jobs:
      - track-and-publish:
          filters:
            branches:
              only:
                - master
  at-0500-UTC-every-day:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - track-and-publish
